# Generated by Django 5.1 on 2024-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('blocked', 'Bloklangan')], default='Active', max_length=50),
        ),
    ]
