# Generated by Django 5.1 on 2024-08-12 05:11

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('external_user', models.CharField(blank=True, max_length=250)),
                ('users', models.ManyToManyField(related_name='project_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
