# Generated by Django 4.2.15 on 2024-08-16 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField()),
                ('document', models.FileField(blank=True, max_length=500, upload_to='')),
                ('related', models.CharField(choices=[('project_related', 'project_related'), ('phase_related', 'phase_related'), ('task_related', 'task_related'), ('expense_related', 'expense_related')], max_length=150)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AlterField(
            model_name='phase',
            name='termination',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='spent_money',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Jarayonda', 'Jarayonda'), ('Tugatilgan', 'Tugatilgan')], max_length=150),
        ),
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.AlterField(
            model_name='project',
            name='termination',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='termination',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.team'),
        ),
    ]
