# Generated by Django 5.1 on 2024-08-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='related',
            field=models.CharField(choices=[('project_related', 'project_related'), ('phase_related', 'phase_related'), ('task_related', 'task_related'), ('expense_related', 'expense_related')], max_length=150),
        ),
    ]
