# Generated by Django 5.1 on 2024-08-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_comments_comment_rename_documents_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='spent_money',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='termination',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='termination',
            field=models.IntegerField(default=0),
        ),
    ]
