# Generated by Django 5.1 on 2024-08-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_budget_alter_project_spent_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='termination',
            field=models.IntegerField(default=0),
        ),
    ]
