# Generated by Django 5.1 on 2024-08-12 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_author_alter_project_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ManyToManyField(related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
