# Generated by Django 5.1 on 2024-08-08 10:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=250)),
                ('related', models.CharField(choices=[('project_related', 'project_related'), ('phase_related', 'phase_related'), ('task_related', 'task_related'), ('expense_related', 'expense_related')], max_length=250)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('external_id', models.UUIDField()),
            ],
        ),
    ]
